### ISSUE TITLE
Token Provider Options no property NonceGenerator?

### ISSUE THREAD

**Issue by Rosscotini** [samueleresca/Blog.TokenAuthGettingStarted#1]
I get the following error when trying to build: 'TokenProviderOptions' does not contain a definition for 'NonceGenerator' and no extension method 'NonceGenerator' accepting a first argument of type 'TokenProviderOptions' could be found (are you missing a using directive or an assembly reference?)

I see in your TokenProviderOptions you do not have a property for NonceGenerator()?

**Comment by pettechbytes** [comment]
Look in the source example, there is a method for NonceGenerator.  It's the last method in the TokenProviderOptions:

https://github.com/samueleresca/Blog.TokenAuthGettingStarted/blob/master/CustomTokenProvider/TokenProviderOptions.cs
